### PR TITLE
proposed first entries of the CV of DimensionRelation

### PR DESCRIPTION
**Pull request by l00mi**
see #47

### CODE REVIEW

**Review by semanticfire — CHANGES_REQUESTED** [review]
This file is not valid TTL, it misses related prefixes

**Comment by l00mi** [comment]
did not copy the whole thing, thank you for noting

**Comment by semanticfire** [comment]
Another thing, I would also add rdfs:label + rdfs:comment, I would consider that bestpractice for vocabularies

**Review by semanticfire — CHANGES_REQUESTED** [review]
* schema prefix has an error
* I think rdfs:label + rdfs:comment are best practice for vocabularies

**Comment by l00mi** [comment]
@semanticfire, both fixed, about the rdfs:label, and rdfs:comment i am not sure, everything else in this realm we use schema:name and schema:description, but it never hurts to have both.

**Review by semanticfire — APPROVED** [review]

**Pull request merged**
